# Reuse the selected upstream register decoder's actual switch, without linking
# the runtime CommandProcessor or inventing a fake command processor object.
function(sl_make_compute_register_decoder input output)
  file(READ "${input}" sl_source)
  string(REPLACE "\r\n" "\n" sl_source "${sl_source}")
  string(REGEX MATCH "static void HwShIgnoreComputeRegister\\([^{}]*\\) \\{\\}" sl_ignore "${sl_source}")
  if(NOT sl_ignore)
    message(FATAL_ERROR "Upstream ignored compute register policy changed; review capture replay")
  endif()
  set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${input}")
  set(sl_begin "static void HwShSetCsRegister(CommandProcessor& cp, uint32_t cmd_offset, uint32_t value) {\n\tauto cs_regs = cp.GetShCtx().GetCs().cs_regs;\n")
  set(sl_end "\n\tcp.GetShCtx().SetCsShader(cs_regs);\n}")
  string(FIND "${sl_source}" "${sl_begin}" sl_start)
  if(sl_start LESS 0)
    message(FATAL_ERROR "Unsupported upstream compute register decoder signature")
  endif()
  string(LENGTH "${sl_begin}" sl_length)
  math(EXPR sl_start "${sl_start}+${sl_length}")
  string(SUBSTRING "${sl_source}" ${sl_start} -1 sl_source)
  string(FIND "${sl_source}" "${sl_end}" sl_stop)
  if(sl_stop LESS 0)
    message(FATAL_ERROR "Unsupported upstream compute register decoder boundary")
  endif()
  string(SUBSTRING "${sl_source}" 0 ${sl_stop} sl_body)
  if(sl_body MATCHES "cp\\.")
    message(FATAL_ERROR "Upstream compute register decoder acquired a runtime dependency")
  endif()
  file(WRITE "${output}" "#include \"common/assert.h\"\n#include \"graphics/guest_gpu/hardwareContext.h\"\n#include \"graphics/guest_gpu/pm4.h\"\nnamespace Libs::Graphics {\n${sl_ignore}\nvoid ShaderLabApplyComputeRegister(HW::CsStageRegisters& cs_regs, uint32_t cmd_offset, uint32_t value) {${sl_body}\n}\n}\n")
endfunction()
