if(NOT EXISTS "${KYTY_ROOT}/src/graphics/shader/recompiler/ShaderRecompiler.h")
  message(FATAL_ERROR "Set KYTY_ROOT to a complete KytyPS5 checkout with its submodules")
endif()
set(KYTY_BUILD_LAUNCHER OFF CACHE BOOL "" FORCE)
set(BUILD_TESTING OFF CACHE BOOL "" FORCE)
# Reuse the upstream standalone-test target's full link closure in this isolated
# build, replacing only its entry-point source. Never edit the selected checkout.
add_subdirectory("${KYTY_ROOT}" "${CMAKE_BINARY_DIR}/kyty" EXCLUDE_FROM_ALL)
if(TARGET libzstd_static)
  target_link_libraries(shader_lab_core PRIVATE libzstd_static)
  target_compile_definitions(shader_lab_core PRIVATE SL_HAVE_ZSTD=1)
  target_link_libraries(shader-lab-tests PRIVATE libzstd_static)
  target_compile_definitions(shader-lab-tests PRIVATE SL_HAVE_ZSTD=1)
endif()
if(NOT TARGET shader_cfg_tests)
  message(FATAL_ERROR "Unsupported KytyPS5 build interface: shader_cfg_tests target absent")
endif()
get_target_property(sl_worker_sources shader_cfg_tests SOURCES)
list(FILTER sl_worker_sources EXCLUDE REGEX "[/\\]shaderCfgTests\\.cpp$")
set_property(TARGET shader_cfg_tests PROPERTY SOURCES "${sl_worker_sources};${CMAKE_CURRENT_LIST_DIR}/../src/kyty_worker.cpp")
set_target_properties(shader_cfg_tests PROPERTIES OUTPUT_NAME shader-kyty-worker RUNTIME_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}" CXX_INCLUDE_WHAT_YOU_USE "" CXX_CLANG_TIDY "")
target_link_libraries(shader_cfg_tests shader_lab_core)
if(MSVC)
  target_compile_options(shader_cfg_tests PRIVATE /EHsc)
else()
  target_compile_options(shader_cfg_tests PRIVATE -fexceptions)
endif()
execute_process(COMMAND git -C "${KYTY_ROOT}" rev-parse HEAD OUTPUT_VARIABLE SL_KYTY_REV OUTPUT_STRIP_TRAILING_WHITESPACE COMMAND_ERROR_IS_FATAL ANY)
execute_process(COMMAND git -C "${KYTY_ROOT}" status --porcelain OUTPUT_VARIABLE SL_KYTY_DIRTY OUTPUT_STRIP_TRAILING_WHITESPACE)
if(SL_KYTY_DIRTY)
  string(APPEND SL_KYTY_REV "-dirty")
endif()
target_compile_definitions(shader_cfg_tests PRIVATE "SL_KYTY_REV=\"${SL_KYTY_REV}\"")
add_custom_target(shader-kyty-worker DEPENDS shader_cfg_tests)
